In [77]:
import numpy as np
from sklearn.model_selection import train_test_split
import os
import matplotlib.pyplot as plt

In [78]:
# Define categories and data containers
categories = [
    'DU_LICH', 'GIAI_TRI', 'GIAO_DUC', 'KHOA_HOC', 'KINH_DOANH', 'PHAP_LUAT', 'SUC_KHOE', 'THE_THAO'
]

data = [[] for _ in categories]

# Function to read and process data from a file
def process_data(category, filename):
    with open(f'./raw_vnexpress_titles/raw_data/{filename}.txt') as file:
        for line in file:
            if line.strip():
                data[category].append(line.strip())

# Populate data and labels
for category, name in enumerate(categories):
    process_data(category, name)

labels = [list(np.ones(len(data[i]), dtype=int) * i) for i in range(len(categories))]


In [79]:
data

[["Khách Việt sẵn sàng chi tiền cho 'du lịch xanh'",
  'Nhà tù Hoả Lò - điểm đến lịch sử hút giới trẻ kỳ nghỉ lễ',
  'Nơi có những ngôi nhà nằm dưới đá',
  'Nhiều người lên núi Bà Đen hàng năm để cầu may',
  'Từ 15/5, tất cả du khách vào phố cổ Hội An phải mua vé',
  '5 nơi có Tết té nước đông vui nhất Thái Lan',
  'Trong lễ Tình nhân người nước nào tặng nhau thìa?',
  'Phụ nữ mặc áo dài được miễn phí tham quan di tích',
  'Đảo Dấu - điểm đến nhiều trải nghiệm',
  '7 ngày ăn và lặn ở vùng biển tây Thái Lan',
  'Phiên chợ ném nhau cầu may diễn ra ở đâu?',
  "Đà Lạt và Sa Pa như 'dãy Alps của châu Á'",
  'Vợ chồng U70 hai tháng đi khắp Việt Nam bằng xe máy',
  "Khách thích 'du lịch xanh' nhưng ngại trả thêm tiền",
  'Công viên đá hoang sơ ở Ninh Thuận',
  'Người dân Huế vui vì VnExpress Marathon hút du khách',
  'Cây vả lộn ngược - điểm đến hút khách ở Naples',
  "Du khách đi chùa ngày xuân: 'Biết đông nhưng vẫn cố'",
  'Lễ hội văn hóa ẩm thực trên 350 món ngon ba miền ở TP HCM',
  'Xếp 

In [80]:
labels

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,


In [120]:
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=0)

In [121]:
from sklearn.model_selection import train_test_split
import numpy as np

# Assuming you have already split the data into X_train and y_train
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=0)



# Calculate the percentage of each label
# percentage_per_label = label_counts / len(y_train_flat) * 100


In [122]:
# Flatten y_train to a 1D array
y_train_flat = np.concatenate(y_train)

# Count the occurrences of each label in y_train
train_counts = np.bincount(y_train_flat, minlength=8)
train_counts

array([625, 623,   0, 605, 624, 634,   0, 624])

In [123]:
train_counts.shape

(8,)

In [124]:
# Flatten y_train to a 1D array
y_test_flat = np.concatenate(y_test)

# Count the occurrences of each label in y_test
test_counts = np.bincount(y_test_flat, minlength=8)
test_counts

array([  0,   0, 613,   0,   0,   0, 619,   0])

In [125]:
test_counts.shape

(8,)

In [126]:
# Flatten y_train to a 1D array
y_label_flat = np.concatenate(labels)

# Count the occurrences of each label in y_label
label_counts = np.bincount(y_label_flat)
label_counts

array([625, 623, 613, 605, 624, 634, 619, 624])